In [125]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData/inst/extdata/kim/Apache.arff') 
df = pd.DataFrame(data[0])

In [126]:
df.head()

AvgCyclomatic  AvgCyclomaticModified  AvgCyclomaticStrict  AvgEssential  \
0           12.0                   11.0                 14.0           4.0   
1            0.0                    0.0                  0.0           0.0   
2            8.0                    7.0                  9.0           4.0   
3            5.0                    5.0                  6.0           2.0   
4            2.0                    2.0                  2.0           1.0   

   AvgLine  AvgLineBlank  AvgLineCode  AvgLineComment  CountLine  \
0     82.0           5.0         61.0             7.0     2195.0   
1      0.0           0.0          0.0             0.0      644.0   
2     54.0           4.0         49.0             1.0     1945.0   
3     37.0           5.0         27.0             5.0     1159.0   
4     21.0           1.0          9.0             3.0      166.0   

   CountLineBlank  ...  CountStmtExe  MaxCyclomatic  MaxCyclomaticModified  \
0           165.0  ...         738.0           51.0                   51.0   
1             1.0  ...           0.0            0.0                    0.0   
2           209.0  ...         877.0           45.0                   26.0   
3           171.0  ...         414.0           25.0                   25.0   
4            15.0  ...          20.0            4.0                    5.0   

   MaxCyclomaticStrict  RatioCommentToCode  SumCyclomatic  \
0                 56.0                0.28          221.0   
1                  0.0                0.00            0.0   
2                 45.0                0.04          256.0   
3                 30.0                0.32          134.0   
4                  4.0                0.73            9.0   

   SumCyclomaticModified  SumCyclomaticStrict  SumEssential  isDefective  
0                  197.0                246.0          81.0     b'buggy'  
1                    0.0                  0.0           0.0     b'clean'  
2                  217.0                277.0         128.0     b'buggy'  
3                  122.0                146.0          63.0     b'clean'  
4                   10.0                  9.0          10.0     b'clean'  

[5 rows x 27 columns]

In [127]:
x = df.drop(['isDefective'],axis = 'columns')
x.head()

AvgCyclomatic  AvgCyclomaticModified  AvgCyclomaticStrict  AvgEssential  \
0           12.0                   11.0                 14.0           4.0   
1            0.0                    0.0                  0.0           0.0   
2            8.0                    7.0                  9.0           4.0   
3            5.0                    5.0                  6.0           2.0   
4            2.0                    2.0                  2.0           1.0   

   AvgLine  AvgLineBlank  AvgLineCode  AvgLineComment  CountLine  \
0     82.0           5.0         61.0             7.0     2195.0   
1      0.0           0.0          0.0             0.0      644.0   
2     54.0           4.0         49.0             1.0     1945.0   
3     37.0           5.0         27.0             5.0     1159.0   
4     21.0           1.0          9.0             3.0      166.0   

   CountLineBlank  ...  CountStmtDecl  CountStmtExe  MaxCyclomatic  \
0           165.0  ...          178.0         738.0           51.0   
1             1.0  ...            0.0           0.0            0.0   
2           209.0  ...          172.0         877.0           45.0   
3           171.0  ...          112.0         414.0           25.0   
4            15.0  ...           10.0          20.0            4.0   

   MaxCyclomaticModified  MaxCyclomaticStrict  RatioCommentToCode  \
0                   51.0                 56.0                0.28   
1                    0.0                  0.0                0.00   
2                   26.0                 45.0                0.04   
3                   25.0                 30.0                0.32   
4                    5.0                  4.0                0.73   

   SumCyclomatic  SumCyclomaticModified  SumCyclomaticStrict  SumEssential  
0          221.0                  197.0                246.0          81.0  
1            0.0                    0.0                  0.0           0.0  
2          256.0                  217.0                277.0         128.0  
3          134.0                  122.0                146.0          63.0  
4            9.0                   10.0                  9.0          10.0  

[5 rows x 26 columns]

In [128]:
x.shape

(194, 26)

In [129]:
buggy = df.iloc[0,26]
clean = df.iloc[1,26]

df.isDefective[df.isDefective == buggy] = 0
df.isDefective[df.isDefective == clean] = 1

df['isDefective'].astype(object).astype(int)

y = df['isDefective']
y = y.astype(int)
y.head()

/tmp/ipykernel_3110/1729702825.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.isDefective[df.isDefective == buggy] = 0
/tmp/ipykernel_3110/1729702825.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.isDefective[df.isDefective == clean] = 1


0    0
1    1
2    0
3    1
4    1
Name: isDefective, dtype: int64

In [130]:
from sklearn.preprocessing import MinMaxScaler

scalar = MinMaxScaler()
scalar.fit(x)
x = scalar.transform(x)

In [131]:
x = pd.DataFrame(x)
x.head()

0        1     2         3             4         5         6   \
0  0.260870  0.34375  0.28  0.148148  1.909211e-08  0.138889  0.352601   
1  0.000000  0.00000  0.00  0.000000  0.000000e+00  0.000000  0.000000   
2  0.173913  0.21875  0.18  0.148148  1.257285e-08  0.111111  0.283237   
3  0.108696  0.15625  0.12  0.074074  8.614734e-09  0.138889  0.156069   
4  0.043478  0.06250  0.04  0.037037  4.889444e-09  0.027778  0.052023   

         7         8         9   ...        16        17        18        19  \
0  0.170732  0.420093  0.194313  ...  0.423810  0.364085  0.160377  0.228700   
1  0.000000  0.119279  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2  0.024390  0.371606  0.246445  ...  0.409524  0.432659  0.141509  0.116592   
3  0.121951  0.219162  0.201422  ...  0.266667  0.204243  0.078616  0.112108   
4  0.073171  0.026571  0.016588  ...  0.023810  0.009867  0.012579  0.022422   

         20        21        22        23        24        25  
0  0.150943  0.049383  0.274194  0.336177  0.258132  0.153992  
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
2  0.121294  0.007055  0.317618  0.370307  0.290661  0.243346  
3  0.080863  0.056437  0.166253  0.208191  0.153200  0.119772  
4  0.010782  0.128748  0.011166  0.017065  0.009444  0.019011  

[5 rows x 26 columns]

In [132]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model, 10)
fit = rfe.fit(x, y)

fit.support_

selected = list(fit.support_)
selected

/home/subhash/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


[False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False]

In [133]:
columns_names = df.columns.values.tolist()
columns_names

['AvgCyclomatic',
 'AvgCyclomaticModified',
 'AvgCyclomaticStrict',
 'AvgEssential',
 'AvgLine',
 'AvgLineBlank',
 'AvgLineCode',
 'AvgLineComment',
 'CountLine',
 'CountLineBlank',
 'CountLineCode',
 'CountLineCodeDecl',
 'CountLineCodeExe',
 'CountLineComment',
 'CountSemicolon',
 'CountStmt',
 'CountStmtDecl',
 'CountStmtExe',
 'MaxCyclomatic',
 'MaxCyclomaticModified',
 'MaxCyclomaticStrict',
 'RatioCommentToCode',
 'SumCyclomatic',
 'SumCyclomaticModified',
 'SumCyclomaticStrict',
 'SumEssential',
 'isDefective']

In [134]:
print(len(columns_names))
print(len(selected))

27
26


In [135]:
for i in range(26):
    if selected[i] == False:
        df = df.drop([columns_names[i]],axis = 'columns')
        
df.head()

AvgEssential  AvgLineComment  CountLine  CountLineCode  CountLineCodeDecl  \
0           4.0             7.0     2195.0         1185.0              191.0   
1           0.0             0.0      644.0            0.0                0.0   
2           4.0             1.0     1945.0         1607.0              185.0   
3           2.0             5.0     1159.0          727.0              137.0   
4           1.0             3.0      166.0           55.0               13.0   

   CountLineCodeExe  CountStmtDecl  MaxCyclomatic  RatioCommentToCode  \
0             907.0          178.0           51.0                0.28   
1               0.0            0.0            0.0                0.00   
2            1096.0          172.0           45.0                0.04   
3             522.0          112.0           25.0                0.32   
4              26.0           10.0            4.0                0.73   

   SumCyclomaticModified isDefective  
0                  197.0           0  
1                    0.0           1  
2                  217.0           0  
3                  122.0           1  
4                   10.0           1

In [136]:
x = df.drop(['isDefective'], axis = 'columns')
x.head()

AvgEssential  AvgLineComment  CountLine  CountLineCode  CountLineCodeDecl  \
0           4.0             7.0     2195.0         1185.0              191.0   
1           0.0             0.0      644.0            0.0                0.0   
2           4.0             1.0     1945.0         1607.0              185.0   
3           2.0             5.0     1159.0          727.0              137.0   
4           1.0             3.0      166.0           55.0               13.0   

   CountLineCodeExe  CountStmtDecl  MaxCyclomatic  RatioCommentToCode  \
0             907.0          178.0           51.0                0.28   
1               0.0            0.0            0.0                0.00   
2            1096.0          172.0           45.0                0.04   
3             522.0          112.0           25.0                0.32   
4              26.0           10.0            4.0                0.73   

   SumCyclomaticModified  
0                  197.0  
1                    0.0  
2                  217.0  
3                  122.0  
4                   10.0

In [137]:
scalar = MinMaxScaler()
scalar.fit(x)
x = scalar.transform(x)

x = pd.DataFrame(x)
x.head()

0         1         2         3         4         5         6  \
0  0.148148  0.170732  0.420093  0.387255  0.279240  0.425822  0.423810   
1  0.000000  0.000000  0.119279  0.000000  0.000000  0.000000  0.000000   
2  0.148148  0.024390  0.371606  0.525163  0.270468  0.514554  0.409524   
3  0.074074  0.121951  0.219162  0.237582  0.200292  0.245070  0.266667   
4  0.037037  0.073171  0.026571  0.017974  0.019006  0.012207  0.023810   

          7         8         9  
0  0.160377  0.049383  0.336177  
1  0.000000  0.000000  0.000000  
2  0.141509  0.007055  0.370307  
3  0.078616  0.056437  0.208191  
4  0.012579  0.128748  0.017065

In [138]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([1, 0, 1, 0, 0], dtype=int32)

In [139]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [140]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [141]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.7450703290555167
ASFM1 : 3.2162023451383304


In [142]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1
        

In [143]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.30055019195042665
Accuracy : 0.6185567010309279
precison : 0.8
Recall : 0.32653061224489793
F1-Score : 0.46376811594202894


In [144]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([0, 1, 0, 0, 1])

In [145]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [146]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 2.7264630889857555
ASFM1 : 0.6268681273449178


In [147]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==0:
        TP += 1
    elif defect == buggy and ag_prediction[i]==1:
        FN += 1
    elif defect == clean and ag_prediction[i]==1:
        TN += 1
    else:
        FP += 1
     

In [148]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.37610828898999865
Accuracy : 0.6701030927835051
precison : 0.7931034482758621
Recall : 0.46938775510204084
F1-Score : 0.5897435897435898


In [149]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([1, 0, 1, 1, 0])

In [150]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [151]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.5335687121238546
ASFM1 : 2.1230754658517523


In [152]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1
 

In [153]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.3840769426991071
Accuracy : 0.6907216494845361
precison : 0.7159090909090909
Recall : 0.6428571428571429
F1-Score : 0.6774193548387097


In [154]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int32)

In [155]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [156]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 1.1209651227648143
ASFM1 : 6.305303255506613


In [157]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1
 

In [158]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.09591830033823641
Accuracy : 0.5103092783505154
precison : 0.8
Recall : 0.04081632653061224
F1-Score : 0.07766990291262134


In [164]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

array([1, 0, 1, 0, 0], dtype=int32)

In [165]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.7450703290555167
ASFM1 : 3.2162023451383304


In [166]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1
 

In [167]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.30055019195042665
Accuracy : 0.6185567010309279
precison : 0.8
Recall : 0.32653061224489793
F1-Score : 0.46376811594202894


In [168]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([0, 1, 0, 0, 1])

In [169]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 2.7264630889857555
ASFM1 : 0.6268681273449178


In [172]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1
 

In [173]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.37610828898999865
Accuracy : 0.6701030927835051
precison : 0.7931034482758621
Recall : 0.46938775510204084
F1-Score : 0.5897435897435898
