In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData/inst/extdata/kim/Safe.arff') 
df = pd.DataFrame(data[0])    

In [2]:
df.head()

AvgCyclomatic  AvgCyclomaticModified  AvgCyclomaticStrict  AvgEssential  \
0            6.0                    6.0                  6.0           1.0   
1            2.0                    2.0                  3.0           1.0   
2            4.0                    4.0                  6.0           1.0   
3            3.0                    2.0                  3.0           1.0   
4            3.0                    3.0                  3.0           1.0   

   AvgLine  AvgLineBlank  AvgLineCode  AvgLineComment  CountLine  \
0     24.0           3.0         19.0             1.0       77.0   
1     12.0           0.0         12.0             0.0      487.0   
2     20.0           1.0         14.0             6.0       29.0   
3     16.0           1.0         14.0             0.0      374.0   
4     18.0           1.0         16.0             0.0      343.0   

   CountLineBlank  ...  CountStmtExe  MaxCyclomatic  MaxCyclomaticModified  \
0            12.0  ...          41.0           15.0                   15.0   
1            44.0  ...         225.0           10.0                   10.0   
2             4.0  ...           9.0            4.0                    4.0   
3            53.0  ...         150.0            7.0                    7.0   
4            43.0  ...         137.0           12.0                   12.0   

   MaxCyclomaticStrict  RatioCommentToCode  SumCyclomatic  \
0                 17.0                0.07           18.0   
1                 12.0                0.04           97.0   
2                  6.0                0.44            4.0   
3                  8.0                0.15           51.0   
4                 12.0                0.17           48.0   

   SumCyclomaticModified  SumCyclomaticStrict  SumEssential  isDefective  
0                   18.0                 20.0           3.0     b'clean'  
1                   97.0                102.0          41.0     b'buggy'  
2                    4.0                  6.0           1.0     b'clean'  
3                   48.0                 56.0          19.0     b'buggy'  
4                   47.0                 53.0          16.0     b'buggy'  

[5 rows x 27 columns]

In [3]:
x = df.drop(['isDefective'],axis = 'columns')
x.head()

AvgCyclomatic  AvgCyclomaticModified  AvgCyclomaticStrict  AvgEssential  \
0            6.0                    6.0                  6.0           1.0   
1            2.0                    2.0                  3.0           1.0   
2            4.0                    4.0                  6.0           1.0   
3            3.0                    2.0                  3.0           1.0   
4            3.0                    3.0                  3.0           1.0   

   AvgLine  AvgLineBlank  AvgLineCode  AvgLineComment  CountLine  \
0     24.0           3.0         19.0             1.0       77.0   
1     12.0           0.0         12.0             0.0      487.0   
2     20.0           1.0         14.0             6.0       29.0   
3     16.0           1.0         14.0             0.0      374.0   
4     18.0           1.0         16.0             0.0      343.0   

   CountLineBlank  ...  CountStmtDecl  CountStmtExe  MaxCyclomatic  \
0            12.0  ...           10.0          41.0           15.0   
1            44.0  ...          106.0         225.0           10.0   
2             4.0  ...            7.0           9.0            4.0   
3            53.0  ...           61.0         150.0            7.0   
4            43.0  ...           57.0         137.0           12.0   

   MaxCyclomaticModified  MaxCyclomaticStrict  RatioCommentToCode  \
0                   15.0                 17.0                0.07   
1                   10.0                 12.0                0.04   
2                    4.0                  6.0                0.44   
3                    7.0                  8.0                0.15   
4                   12.0                 12.0                0.17   

   SumCyclomatic  SumCyclomaticModified  SumCyclomaticStrict  SumEssential  
0           18.0                   18.0                 20.0           3.0  
1           97.0                   97.0                102.0          41.0  
2            4.0                    4.0                  6.0           1.0  
3           51.0                   48.0                 56.0          19.0  
4           48.0                   47.0                 53.0          16.0  

[5 rows x 26 columns]

In [4]:
x.shape

(56, 26)

In [5]:
from sklearn.preprocessing import MinMaxScaler

scalar = MinMaxScaler()
scalar.fit(x)
x = scalar.transform(x)

In [6]:
x = pd.DataFrame(x)
x.head()

0         1         2    3     4    5         6      7         8   \
0  0.857143  0.857143  0.545455  0.5  0.48  0.3  0.500000  0.125  0.077895   
1  0.285714  0.285714  0.272727  0.5  0.24  0.0  0.315789  0.000  0.509474   
2  0.571429  0.571429  0.545455  0.5  0.40  0.1  0.368421  0.750  0.027368   
3  0.428571  0.285714  0.272727  0.5  0.32  0.1  0.368421  0.000  0.390526   
4  0.428571  0.428571  0.272727  0.5  0.36  0.1  0.421053  0.000  0.357895   

         9   ...        16        17        18        19        20        21  \
0  0.100840  ...  0.046512  0.112022  0.500000  0.517241  0.459459  0.009524   
1  0.369748  ...  0.604651  0.614754  0.333333  0.344828  0.324324  0.005442   
2  0.033613  ...  0.029070  0.024590  0.133333  0.137931  0.162162  0.059864   
3  0.445378  ...  0.343023  0.409836  0.233333  0.241379  0.216216  0.020408   
4  0.361345  ...  0.319767  0.374317  0.400000  0.413793  0.324324  0.023129   

         22        23        24        25  
0  0.128571  0.129496  0.138889  0.055556  
1  0.692857  0.697842  0.708333  0.759259  
2  0.028571  0.028777  0.041667  0.018519  
3  0.364286  0.345324  0.388889  0.351852  
4  0.342857  0.338129  0.368056  0.296296  

[5 rows x 26 columns]

In [7]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 1, 0, 1, 1], dtype=int32)

In [8]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [9]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

In [10]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 3.1460765559710167
ASFM1 : 11.409321073504238


In [11]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0


for i in range(56):
    
    defect = df.iloc[i,26]
    buggy = df.iloc[1,26]
    clean = df.iloc[0,26]
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1
        

In [12]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

accuracy = (TP+TN)/len(df)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")

MCC : 0.42167482785855936
Accuracy : 0.7321428571428571


In [13]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([0, 1, 0, 0, 0])

In [14]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [15]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 4.263157472962583
ASFM1 : 14.49518020820765


In [16]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0


for i in range(56):
    
    defect = df.iloc[i,26]
    buggy = df.iloc[1,26]
    clean = df.iloc[0,26]
    
    if defect == buggy and ag_prediction[i]==1:
        TP += 1
    elif defect == buggy and ag_prediction[i]==0:
        FN += 1
    elif defect == clean and ag_prediction[i]==0:
        TN += 1
    else:
        FP += 1
    

In [17]:
#Matthew Correlation Coefficient
import math

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

accuracy = (TP+TN)/len(df)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")

MCC : 0.43064433753916403
Accuracy : 0.7142857142857143


In [18]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 1, 0, 1, 1])

In [19]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [20]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 3.041005419280423
ASFM1 : 11.155546132884902


In [23]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0


for i in range(56):
    
    defect = df.iloc[i,26]
    buggy = df.iloc[1,26]
    clean = df.iloc[0,26]
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1
   

In [24]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

accuracy = (TP+TN)/len(df)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")

MCC : 0.4624972900628803
Accuracy : 0.75


In [25]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int32)

In [26]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [27]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 4.842970493270617
ASFM1 : 19.304274130380797


In [28]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0


for i in range(56):
    
    defect = df.iloc[i,26]
    buggy = df.iloc[1,26]
    clean = df.iloc[0,26]
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1
  

In [29]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

accuracy = (TP+TN)/len(df)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")

MCC : 0.23924685418842448
Accuracy : 0.6428571428571429


In [30]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

array([0, 1, 0, 1, 1], dtype=int32)

In [31]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [32]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 3.1460765559710167
ASFM1 : 11.409321073504238


In [35]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0


for i in range(56):
    
    defect = df.iloc[i,26]
    buggy = df.iloc[1,26]
    clean = df.iloc[0,26]
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1
  

In [36]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

accuracy = (TP+TN)/len(df)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")

MCC : 0.42167482785855936
Accuracy : 0.7321428571428571


In [37]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([0, 1, 0, 0, 0])

In [38]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [39]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 4.263157472962583
ASFM1 : 14.49518020820765


In [40]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0


for i in range(56):
    
    defect = df.iloc[i,26]
    buggy = df.iloc[1,26]
    clean = df.iloc[0,26]
    
    if defect == buggy and birch_prediction[i]==1:
        TP += 1
    elif defect == buggy and birch_prediction[i]==0:
        FN += 1
    elif defect == clean and birch_prediction[i]==0:
        TN += 1
    else:
        FP += 1
 

In [41]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

accuracy = (TP+TN)/len(df)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")

MCC : 0.43064433753916403
Accuracy : 0.7142857142857143
