In [33]:
import pandas as pd
import numpy as np

from numpy import unique
from numpy import where
from matplotlib import pyplot

df = pd.read_csv('./DefectData/inst/extdata/terapromise/ck/zuzel.csv')

In [35]:
df.head()

name  version              name.1  wmc  dit  noc  cbo  rfc  lcom  ca  ...  \
0  Zuzel        1      windows.tabela    6    6    0    0   27     7   0  ...   
1  Zuzel        1  manadzerData.Motor   10    1    0   14   11     3  14  ...   
2  Zuzel        1     bean.ProfilBean    5    1    0    2   19     0   0  ...   
3  Zuzel        1        proby.opener    2    1    0    3   17     1   0  ...   
4  Zuzel        1   windows.Formularz   15    6    0    7   49    73   3  ...   

        dam  moa       mfa       cam  ic  cbm        amc  max_cc  avg_cc  bug  
0  1.000000    0  0.992089  1.000000   0    0  27.500000       2     1.5    0  
1  1.000000    0  0.000000  0.533333   0    0   5.800000       1     0.8    0  
2  1.000000    0  0.000000  0.466667   0    0  16.000000       2     1.0    0  
3  0.000000    0  0.000000  0.500000   0    0  46.500000       2     1.0    0  
4  0.916667    2  0.978159  0.355556   0    0  26.466667       3     1.6    1  

[5 rows x 24 columns]

In [36]:
df.shape

(29, 24)

In [37]:
x = df.drop(['name','version','name.1'],axis='columns')

In [38]:
x = pd.DataFrame(x)
x.head()

wmc  dit  noc  cbo  rfc  lcom  ca  ce  npm     lcom3  ...       dam  moa  \
0    6    6    0    0   27     7   0   0    1  0.700000  ...  1.000000    0   
1   10    1    0   14   11     3  14   0   10  0.666667  ...  1.000000    0   
2    5    1    0    2   19     0   0   2    5  0.000000  ...  1.000000    0   
3    2    1    0    3   17     1   0   3    2  2.000000  ...  0.000000    0   
4   15    6    0    7   49    73   3   6    1  0.863095  ...  0.916667    2   

        mfa       cam  ic  cbm        amc  max_cc  avg_cc  bug  
0  0.992089  1.000000   0    0  27.500000       2     1.5    0  
1  0.000000  0.533333   0    0   5.800000       1     0.8    0  
2  0.000000  0.466667   0    0  16.000000       2     1.0    0  
3  0.000000  0.500000   0    0  46.500000       2     1.0    0  
4  0.978159  0.355556   0    0  26.466667       3     1.6    1  

[5 rows x 21 columns]

In [39]:
from sklearn.preprocessing import MinMaxScaler

scalar = MinMaxScaler()
scalar.fit(x)
x = scalar.transform(x)

In [40]:
x = pd.DataFrame(x)

In [41]:
x.head()

0    1    2         3         4         5         6         7   \
0  0.108696  1.0  0.0  0.000000  0.268817  0.009901  0.000000  0.000000   
1  0.195652  0.0  0.0  0.333333  0.096774  0.004243  0.358974  0.000000   
2  0.086957  0.0  0.0  0.047619  0.182796  0.000000  0.000000  0.222222   
3  0.021739  0.0  0.0  0.071429  0.161290  0.001414  0.000000  0.333333   
4  0.304348  1.0  0.0  0.166667  0.505376  0.103253  0.076923  0.666667   

         8         9   ...        11   12        13        14   15   16  \
0  0.000000  0.350000  ...  1.000000  0.0  0.992089  1.000000  0.0  0.0   
1  0.409091  0.333333  ...  1.000000  0.0  0.000000  0.429348  0.0  0.0   
2  0.181818  0.000000  ...  1.000000  0.0  0.000000  0.347826  0.0  0.0   
3  0.045455  1.000000  ...  0.000000  0.0  0.000000  0.388587  0.0  0.0   
4  0.000000  0.431548  ...  0.916667  0.5  0.978159  0.211957  0.0  0.0   

         17        18        19    20  
0  0.300979  0.133333  0.381359  0.00  
1  0.063479  0.066667  0.203392  0.00  
2  0.175115  0.133333  0.254239  0.00  
3  0.508929  0.133333  0.254239  0.00  
4  0.289670  0.200000  0.406783  0.25  

[5 rows x 21 columns]

In [42]:
from sklearn.cluster import KMeans

In [11]:
kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)

In [12]:
kmeans_prediction

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0], dtype=int32)

In [13]:
from sklearn.cluster import AffinityPropagation

af_model = AffinityPropagation(random_state = None)

af_model.fit(x)
af_prediction = af_model.labels_

In [14]:
af_prediction

array([0, 3, 3, 1, 2, 3, 2, 3, 2, 0, 3, 0, 1, 3, 1, 3, 3, 2, 3, 3, 1, 2,
       0, 2, 2, 3, 1, 2, 3])

In [15]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

ag_model.fit(x)
ag_prediction = ag_model.labels_

In [16]:
ag_prediction

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1])

In [17]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

birch_model.fit(x)
birch_prediction = birch_model.labels_

In [18]:
birch_prediction

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1])

In [19]:
from sklearn.cluster import DBSCAN

dbscan_model = DBSCAN()

dbscan_model.fit(x)
dbscan_prediction = dbscan_model.labels_

In [20]:
dbscan_prediction

array([-1,  0,  0, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1,  0, -1, -1, -1,
       -1,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1,  0])

In [21]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_

In [22]:
miniBatchKmeans_prediction

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1], dtype=int32)

In [23]:
from sklearn.cluster import MeanShift

meanShift_model = MeanShift()

meanShift_model.fit(x)
meanShift_prediction = meanShift_model.labels_

In [24]:
meanShift_prediction

array([0, 0, 0, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0])

In [25]:
from sklearn.cluster import OPTICS

optics_model = OPTICS()

optics_model.fit(x)
optics_prediction = optics_model.labels_

In [26]:
optics_prediction

array([ 0,  1,  1, -1,  0, -1,  0,  1,  0,  0,  1,  0, -1,  1, -1, -1, -1,
        0,  1,  1, -1,  0,  0,  0,  0, -1, -1,  0,  1])

In [27]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

SC_model.fit(x)
SC_prediction = SC_model.labels_

In [28]:
SC_prediction

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0], dtype=int32)

In [31]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

gm_model.fit(x)
gm_prediction = gm_model.predict(x)

In [32]:
gm_prediction

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1])

In [ ]:
#Visualising results of Gaussian Mixture algorithm

from numpy import unique