In [54]:
from scipy.io import arff
import pandas as pd
import numpy as np
import math

from numpy import unique
from numpy import where
from matplotlib import pyplot

data = arff.loadarff('./DefectData/inst/extdata/kim/Zxing.arff') 
df = pd.DataFrame(data[0])

In [55]:
df.head()

AvgCyclomatic  AvgCyclomaticModified  AvgCyclomaticStrict  AvgEssential  \
0            2.0                    2.0                  2.0           1.0   
1            1.0                    1.0                  1.0           1.0   
2            1.0                    1.0                  1.0           1.0   
3            1.0                    1.0                  1.0           1.0   
4            2.0                    2.0                  2.0           1.0   

   AvgLine  AvgLineBlank  AvgLineCode  AvgLineComment  CountLine  \
0      7.0           0.0          7.0             1.0       66.0   
1      7.0           0.0          6.0             1.0       17.0   
2      6.0           1.0          5.0             0.0       75.0   
3     10.0           0.0         10.0             1.0      176.0   
4     37.0           0.0         35.0             1.0      560.0   

   CountLineBlank  ...  CountStmtExe  MaxCyclomatic  MaxCyclomaticModified  \
0             6.0  ...          17.0            4.0                    4.0   
1             2.0  ...           2.0            1.0                    1.0   
2            20.0  ...           9.0            1.0                    1.0   
3            17.0  ...          86.0            4.0                    4.0   
4            32.0  ...          58.0            5.0                    5.0   

   MaxCyclomaticStrict  RatioCommentToCode  SumCyclomatic  \
0                  5.0                0.80            9.0   
1                  1.0                0.15            2.0   
2                  1.0                0.00            9.0   
3                  4.0                0.38           20.0   
4                  9.0                0.09           24.0   

   SumCyclomaticModified  SumCyclomaticStrict  SumEssential  isDefective  
0                    9.0                 10.0           4.0     b'clean'  
1                    2.0                  2.0           2.0     b'buggy'  
2                    9.0                  9.0           9.0     b'clean'  
3                   20.0                 20.0          12.0     b'clean'  
4                   24.0                 29.0          20.0     b'buggy'  

[5 rows x 27 columns]

In [56]:
x = df.drop(['isDefective'],axis = 'columns')
x.head()

AvgCyclomatic  AvgCyclomaticModified  AvgCyclomaticStrict  AvgEssential  \
0            2.0                    2.0                  2.0           1.0   
1            1.0                    1.0                  1.0           1.0   
2            1.0                    1.0                  1.0           1.0   
3            1.0                    1.0                  1.0           1.0   
4            2.0                    2.0                  2.0           1.0   

   AvgLine  AvgLineBlank  AvgLineCode  AvgLineComment  CountLine  \
0      7.0           0.0          7.0             1.0       66.0   
1      7.0           0.0          6.0             1.0       17.0   
2      6.0           1.0          5.0             0.0       75.0   
3     10.0           0.0         10.0             1.0      176.0   
4     37.0           0.0         35.0             1.0      560.0   

   CountLineBlank  ...  CountStmtDecl  CountStmtExe  MaxCyclomatic  \
0             6.0  ...            8.0          17.0            4.0   
1             2.0  ...            7.0           2.0            1.0   
2            20.0  ...           36.0           9.0            1.0   
3            17.0  ...           18.0          86.0            4.0   
4            32.0  ...           48.0          58.0            5.0   

   MaxCyclomaticModified  MaxCyclomaticStrict  RatioCommentToCode  \
0                    4.0                  5.0                0.80   
1                    1.0                  1.0                0.15   
2                    1.0                  1.0                0.00   
3                    4.0                  4.0                0.38   
4                    5.0                  9.0                0.09   

   SumCyclomatic  SumCyclomaticModified  SumCyclomaticStrict  SumEssential  
0            9.0                    9.0                 10.0           4.0  
1            2.0                    2.0                  2.0           2.0  
2            9.0                    9.0                  9.0           9.0  
3           20.0                   20.0                 20.0          12.0  
4           24.0                   24.0                 29.0          20.0  

[5 rows x 26 columns]

In [57]:
x.shape

(399, 26)

In [59]:
from sklearn.preprocessing import MinMaxScaler

scalar = MinMaxScaler()
scalar.fit(x)
x = scalar.transform(x)

In [60]:
x = pd.DataFrame(x)
x.head()

0         1         2         3         4      5         6       7   \
0  0.090909  0.142857  0.074074  0.142857  0.069307  0.000  0.082353  0.0625   
1  0.045455  0.071429  0.037037  0.142857  0.069307  0.000  0.070588  0.0625   
2  0.045455  0.071429  0.037037  0.142857  0.059406  0.125  0.058824  0.0000   
3  0.045455  0.071429  0.037037  0.142857  0.099010  0.000  0.117647  0.0625   
4  0.090909  0.142857  0.074074  0.142857  0.366337  0.000  0.411765  0.0625   

         8         9   ...        16        17        18        19        20  \
0  0.054867  0.081081  ...  0.056911  0.069672  0.076923  0.137931  0.092593   
1  0.011504  0.027027  ...  0.048780  0.008197  0.019231  0.034483  0.018519   
2  0.062832  0.270270  ...  0.284553  0.036885  0.019231  0.034483  0.018519   
3  0.152212  0.229730  ...  0.138211  0.352459  0.076923  0.137931  0.074074   
4  0.492035  0.432432  ...  0.382114  0.237705  0.096154  0.172414  0.166667   

         21        22        23        24        25  
0  0.235294  0.088235  0.108434  0.086207  0.046512  
1  0.044118  0.019608  0.024096  0.017241  0.023256  
2  0.000000  0.088235  0.108434  0.077586  0.104651  
3  0.111765  0.196078  0.240964  0.172414  0.139535  
4  0.026471  0.235294  0.289157  0.250000  0.232558  

[5 rows x 26 columns]

In [61]:
buggy = df.iloc[1,26]
clean = df.iloc[0,26]

df.isDefective[df.isDefective == buggy] = 0
df.isDefective[df.isDefective == clean] = 1

df['isDefective'].astype(object).astype(int)

y = df['isDefective']
y = y.astype(int)
y.head()

/tmp/ipykernel_5799/3320235853.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.isDefective[df.isDefective == buggy] = 0
/tmp/ipykernel_5799/3320235853.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.isDefective[df.isDefective == clean] = 1


0    1
1    0
2    1
3    1
4    0
Name: isDefective, dtype: int64

In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
rfe = RFE(model, 6)
fit = rfe.fit(x, y)

fit.support_

selected = list(fit.support_)
selected

/home/subhash/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=6 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


[False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False]

In [63]:
columns_names = df.columns.values.tolist()
columns_names

['AvgCyclomatic',
 'AvgCyclomaticModified',
 'AvgCyclomaticStrict',
 'AvgEssential',
 'AvgLine',
 'AvgLineBlank',
 'AvgLineCode',
 'AvgLineComment',
 'CountLine',
 'CountLineBlank',
 'CountLineCode',
 'CountLineCodeDecl',
 'CountLineCodeExe',
 'CountLineComment',
 'CountSemicolon',
 'CountStmt',
 'CountStmtDecl',
 'CountStmtExe',
 'MaxCyclomatic',
 'MaxCyclomaticModified',
 'MaxCyclomaticStrict',
 'RatioCommentToCode',
 'SumCyclomatic',
 'SumCyclomaticModified',
 'SumCyclomaticStrict',
 'SumEssential',
 'isDefective']

In [64]:
print(len(columns_names))
print(len(selected))

27
26


In [65]:
for i in range(26):
    if selected[i] == False:
        df = df.drop([columns_names[i]],axis = 'columns')
        
df.head()

AvgEssential  AvgLineBlank  CountLineCodeExe  MaxCyclomatic  \
0           1.0           0.0              17.0            4.0   
1           1.0           0.0               2.0            1.0   
2           1.0           1.0               9.0            1.0   
3           1.0           0.0              91.0            4.0   
4           1.0           0.0             388.0            5.0   

   MaxCyclomaticModified  SumCyclomatic isDefective  
0                    4.0            9.0           1  
1                    1.0            2.0           0  
2                    1.0            9.0           1  
3                    4.0           20.0           1  
4                    5.0           24.0           0

In [66]:
x = df.drop(['isDefective'], axis = 'columns')
x.head()

AvgEssential  AvgLineBlank  CountLineCodeExe  MaxCyclomatic  \
0           1.0           0.0              17.0            4.0   
1           1.0           0.0               2.0            1.0   
2           1.0           1.0               9.0            1.0   
3           1.0           0.0              91.0            4.0   
4           1.0           0.0             388.0            5.0   

   MaxCyclomaticModified  SumCyclomatic  
0                    4.0            9.0  
1                    1.0            2.0  
2                    1.0            9.0  
3                    4.0           20.0  
4                    5.0           24.0

In [67]:
scalar = MinMaxScaler()
scalar.fit(x)
x = scalar.transform(x)

x = pd.DataFrame(x)
x.head()

0      1         2         3         4         5
0  0.142857  0.000  0.043814  0.076923  0.137931  0.088235
1  0.142857  0.000  0.005155  0.019231  0.034483  0.019608
2  0.142857  0.125  0.023196  0.019231  0.034483  0.088235
3  0.142857  0.000  0.234536  0.076923  0.137931  0.196078
4  0.142857  0.000  1.000000  0.096154  0.172414  0.235294

In [68]:
from sklearn.cluster import KMeans

kmeans_model = KMeans(n_clusters = 2)
kmeans_model.fit(x)

kmeans_prediction = kmeans_model.predict(x)
x['cluster'] = kmeans_prediction

kmeans_prediction[:5]

array([0, 0, 0, 0, 1], dtype=int32)

In [69]:
def ASFM(DataFrame):
    SFM = 0
    
    x,y = DataFrame.shape
    
    for i in range(x):
        for j in range(y-1):
            SFM += DataFrame.iloc[i,j]
    
    return SFM/x

In [70]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.48512330061239883
ASFM1 : 2.283344239285693


In [71]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and kmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and kmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and kmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1
  

In [72]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.16050860544970647
Accuracy : 0.706766917293233
precison : 0.5121951219512195
Recall : 0.17796610169491525
F1-Score : 0.2641509433962264


In [73]:
from sklearn.cluster import AgglomerativeClustering

ag_model = AgglomerativeClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
ag_model.fit(x)
ag_prediction = ag_model.labels_
x['cluster'] = ag_prediction

ag_prediction[:5]

array([0, 0, 0, 0, 0])

In [74]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.5249797754898891
ASFM1 : 2.6666214425079087


In [77]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and ag_prediction[i]==1:
        TP += 1
    elif defect == buggy and ag_prediction[i]==0:
        FN += 1
    elif defect == clean and ag_prediction[i]==0:
        TN += 1
    else:
        FP += 1
     

In [78]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.06592013858489264
Accuracy : 0.6917293233082706
precison : 0.4074074074074074
Recall : 0.09322033898305085
F1-Score : 0.15172413793103448


In [79]:
from sklearn.mixture import GaussianMixture

gm_model = GaussianMixture(n_components = 2)

x = x.drop(['cluster'],axis = 'columns')
gm_model.fit(x)
gm_prediction = gm_model.predict(x)
x['cluster'] = gm_prediction

gm_prediction[:5]

array([0, 0, 0, 1, 1])

In [80]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.36792865524824464
ASFM1 : 1.3636949526523974


In [81]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and gm_prediction[i]==1:
        TP += 1
    elif defect == buggy and gm_prediction[i]==0:
        FN += 1
    elif defect == clean and gm_prediction[i]==0:
        TN += 1
    else:
        FP += 1
 

In [82]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.16983491392110514
Accuracy : 0.6516290726817042
precison : 0.4132231404958678
Recall : 0.423728813559322
F1-Score : 0.41841004184100417


In [83]:
from sklearn.cluster import SpectralClustering

SC_model = SpectralClustering(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
SC_model.fit(x)

SC_prediction = SC_model.labels_
x['cluster'] = SC_prediction

SC_prediction[:5]

array([0, 0, 0, 0, 0], dtype=int32)

In [84]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]


In [85]:
ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.5516581670286301
ASFM1 : 2.910640506305069


In [86]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and SC_prediction[i]==1:
        TP += 1
    elif defect == buggy and SC_prediction[i]==0:
        FN += 1
    elif defect == clean and SC_prediction[i]==0:
        TN += 1
    else:
        FP += 1
 

In [87]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.10281555826553378
Accuracy : 0.7042606516290727
precison : 0.5
Recall : 0.0847457627118644
F1-Score : 0.14492753623188406


In [88]:
from sklearn.cluster import MiniBatchKMeans

miniBatchKmeans_model = MiniBatchKMeans(n_clusters = 2)

x = x.drop(['cluster'],axis = 'columns')
miniBatchKmeans_model.fit(x)
miniBatchKmeans_prediction = miniBatchKmeans_model.labels_
x['cluster'] = miniBatchKmeans_prediction

miniBatchKmeans_prediction[:5]

array([0, 0, 0, 0, 1], dtype=int32)

In [89]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 0.4775002950568973
ASFM1 : 2.22224206101713


In [90]:
#ASFM1 value is greater than ASFM0, so label 1 will represent defected software and 0 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and miniBatchKmeans_prediction[i]==1:
        TP += 1
    elif defect == buggy and miniBatchKmeans_prediction[i]==0:
        FN += 1
    elif defect == clean and miniBatchKmeans_prediction[i]==0:
        TN += 1
    else:
        FP += 1
 

In [91]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.15757075170156637
Accuracy : 0.7042606516290727
precison : 0.5
Recall : 0.1864406779661017
F1-Score : 0.271604938271605


In [92]:
from sklearn.cluster import Birch

birch_model = Birch(threshold=0.01, n_clusters=2)

x = x.drop(['cluster'],axis = 'columns')
birch_model.fit(x)
birch_prediction = birch_model.labels_
x['cluster'] = birch_prediction

birch_prediction[:5]

array([1, 1, 1, 1, 1])

In [93]:
df0 = x[x.cluster==0]
df1 = x[x.cluster==1]

ASFM0 = ASFM(df0)
ASFM1 = ASFM(df1)

print(f"ASFM0 : {ASFM0}")
print(f"ASFM1 : {ASFM1}")

ASFM0 : 2.6666214425079087
ASFM1 : 0.5249797754898891


In [94]:
#ASFM0 value is greater than ASFM1, so label 0 will represent defected software and 1 represents non-defected 
#software



TP = 0
FN = 0
TN = 0
FP = 0

n,m = df.shape


for i in range(n):
    
    defect = df.iloc[i,m-1]
    buggy = 0
    clean = 1
    
    if defect == buggy and birch_prediction[i]==0:
        TP += 1
    elif defect == buggy and birch_prediction[i]==1:
        FN += 1
    elif defect == clean and birch_prediction[i]==1:
        TN += 1
    else:
        FP += 1
 

In [95]:
#Matthew Correlation Coefficient

MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
accuracy = (TP+TN)/len(df)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
#F1-Score
F = 2*(precision*recall)/(precision+recall)

print(f"MCC : {MCC}")
print(f"Accuracy : {accuracy}")
print(f"precison : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {F}")

MCC : 0.06592013858489264
Accuracy : 0.6917293233082706
precison : 0.4074074074074074
Recall : 0.09322033898305085
F1-Score : 0.15172413793103448
